### PR TITLE
Create Lyrics.js

### PR DESCRIPTION
**Pull request by berusvn**

### CODE REVIEW

**Comment by LoryPelli** [comment]
Who are you?

**Comment by Meqativ** [comment]
> Who are you?
they're berusvn

**Comment by Tetracyl** [comment]
true..

**Review by Tetracyl — CHANGES_REQUESTED** [review]
ezgif-1-1739e21625

The embed doesn't always properly update when the buttons are pressed.

**Comment by LoryPelli** [comment]
Please make that it will use song history for options as the play command

**Comment by berusvn** [comment]
idk, i just apply paginate from messagehelper

**Comment by LoryPelli** [comment]
> idk, i just apply paginate from messagehelper

I was talking with tetracyl

**Review by berusvn — COMMENTED** [review]
maybe we just fix paginate from msghelper

**Comment by Tetracyl** [comment]
There is nothing wrong with the paginate function since it works for shards command and the queue command.

**Comment by berusvn** [comment]
> There is nothing wrong with the paginate function since it works for shards command and the queue command.

hmm, maybe i should recheck the code

**Review by Tetracyl — CHANGES_REQUESTED** [review]
The lyrics variable is never defined

**Comment by berusvn** [comment]
> The lyrics variable is never defined. Please test your code before pushing another commit.

when I deleted console.log I deleted the variable assignment sr about that @@

**Comment by Tetracyl** [comment]
Thanks, will test again when I have time

**Review by Tetracyl — APPROVED** [review]

**Comment by Tetracyl** [comment]
Thanks for the pr @berusvn

**Pull request merged**
